### ISSUE TITLE
Null Pointer exception when logging in

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wiwimi/webagenda#18]
```
What steps will reproduce the problem?
1.Log into the system
2. Run the test emp search or any of the test classes

Returns a null pointer from the thread after a certain period of time.... 
Output is as follows when 
running the TestEmpSearch.java file....

<code>
SELECT * FROM `WebAgenda`.`EMPLOYEE` WHERE empID = 5;
SELECT * FROM `WebAgenda`.`EMPLOYEE` WHERE active = true;
SELECT * FROM `WebAgenda`.`EMPLOYEE` WHERE supervisorID = 3;
---------- Search Results by ID 5 ----------
5;2;Quinn;Hart;null;null;user5;null;null;Cook;1a;null;true

---------- Search Results by Active State True ----------
1;0;Chaney;Henson;null;null;user1;null;null;General Manager;2a;null;true
2;1;Ray;Oliver;null;null;user2;null;null;Executive Chef;1a;null;true
3;1;Audra;Gordon;null;null;user3;null;null;Front of House Mgr.;1a;null;true
4;2;Rina;Pruitt;null;null;user4;null;null;Cook;1a;null;true
5;2;Quinn;Hart;null;null;user5;null;null;Cook;1a;null;true
6;2;Sierra;Dean;null;null;user6;null;null;Cook;1a;null;true
7;3;Sylvia;Dyer;null;null;user7;null;null;Waiter;1a;null;true
8;3;Kay;Bates;null;null;user8;null;null;Waiter;1a;null;true
9;3;Luke;Garrison;null;null;user9;null;null;Waiter;1a;null;true

---------- Search Results by Supervisor 3 ----------
7;3;Sylvia;Dyer;null;null;user7;null;null;Waiter;1a;null;true
8;3;Kay;Bates;null;null;user8;null;null;Waiter;1a;null;true
9;3;Luke;Garrison;null;null;user9;null;null;Waiter;1a;null;true
1813 time to remove
true is available
313 time to remove
true is available
-1188 time to remove
true is available
Time to close
Exception in thread "Thread-0" java.lang.NullPointerException
    at utilities.DoubleLinkedList.remove(DoubleLinkedList.java:271)
    at persistence.Broker$BrokerConMonitor.run(Broker.java:197)
</code>

```

Original issue reported on code.google.com by `markhazl...@gmail.com` on 25 Feb 2010 at 4:53

**Comment by GoogleCodeExporter** [comment]
```
Not getting the issue you specified. I notice that the exception is called when 
the
timer runs out, or thereabouts. If we have the same revisions, this shouldn't 
be an
issue unless its a project setting (relating to the double linked list) or a 
database
issue. I will be working on this.

SELECT * FROM `WebAgenda`.`EMPLOYEE` WHERE empID = 5;
SELECT * FROM `WebAgenda`.`EMPLOYEE` WHERE active = true;
SELECT * FROM `WebAgenda`.`EMPLOYEE` WHERE supervisorID = 3;
---------- Search Results by ID 5 ----------
5;2;Quinn;Hart;null;null;user5;null;null;Cook;1a;null;true

---------- Search Results by Active State True ----------
1;0;Chaney;Henson;null;null;user1;null;null;General Manager;2a;null;true
2;1;Ray;Oliver;null;null;user2;null;null;Executive Chef;1a;null;true
3;1;Audra;Gordon;null;null;user3;null;null;Front of House Mgr.;1a;null;true
4;2;Rina;Pruitt;null;null;user4;null;null;Cook;1a;null;true
5;2;Quinn;Hart;null;null;user5;null;null;Cook;1a;null;true
6;2;Sierra;Dean;null;null;user6;null;null;Cook;1a;null;true
7;3;Sylvia;Dyer;null;null;user7;null;null;Waiter;1a;null;true
8;3;Kay;Bates;null;null;user8;null;null;Waiter;1a;null;true
9;3;Luke;Garrison;null;null;user9;null;null;Waiter;1a;null;true

---------- Search Results by Supervisor 3 ----------
7;3;Sylvia;Dyer;null;null;user7;null;null;Waiter;1a;null;true
8;3;Kay;Bates;null;null;user8;null;null;Waiter;1a;null;true
9;3;Luke;Garrison;null;null;user9;null;null;Waiter;1a;null;true
2108 time to remove
true is available
608 time to remove
true is available
-893 time to remove
true is available
-2393 time to remove
true is available
```

Original comment by `Initial....@gmail.com` on 25 Feb 2010 at 5:26
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Bug is fixed. Ended up being an issue with eclipse not using latest revision,
updating to head. A revert to the package fixed it.
```

Original comment by `Initial....@gmail.com` on 25 Feb 2010 at 5:39
- Changed state: **Fixed**
