### ISSUE TITLE
Cannot find utilities/DoubleLinkedList upon login

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wiwimi/webagenda#19]
```
What steps will reproduce the problem?
1. Login to the system after running it on the server
2. Blank login page should occur
3. Look at console

Error

WARNING: StandardWrapperValve[Login]: PWC1406: Servlet.service() for servlet 
Login threw 
exception
java.lang.NoClassDefFoundError: utilities/DoubleLinkedList
    at persistence.Broker.<init>(Broker.java:29)
    at persistence.EmployeeBroker.<init>(EmployeeBroker.java:25)
    at persistence.EmployeeBroker.getBroker(EmployeeBroker.java:42)
    at ui.Login.doPost(Login.java:72)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:754)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
    at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1523)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:279)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:188)
    at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:641)
    at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
    at 
com.sun.enterprise.web.PESessionLockingStandardPipeline.invoke(PESessionLockingS
tandardPipe
line.java:85)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:185)
    at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:332)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:233)
    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:165)
    at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:791)
    at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:693)
    at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:954)
    at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:170)
    at 
com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.
java:135)
    at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:102)
    at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:88)
    at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:76)
    at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:53)
    at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:57)
    at com.sun.grizzly.ContextTask.run(ContextTask.java:69)
    at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:330)
    at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:309)
    at java.lang.Thread.run(Thread.java:637)
Caused by: java.lang.ClassNotFoundException: utilities.DoubleLinkedList
    at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
    at org.glassfish.web.loader.WebappClassLoader.findClass(WebappClassLoader.java:949)
    at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1420)
    at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:398)
    ... 30 more

```

Original issue reported on code.google.com by `markhazl...@gmail.com` on 25 Feb 2010 at 5:01

**Comment by GoogleCodeExporter** [comment]
```
Temporary Fix found.  The jar files that Eclipse is putting on the server aren't
being accessed properly.  For the time being, you can copy the jar files 
manually to
the glassfish server.

In the project root, lib folder, you will find the following two files:
DoubleLinkedList-DK.jar
mysql-connector-java-5.1.11-bin.jar

Copy both of these files to the glassfish server-wide lib folder.  In my case on
Windows, this would be at "C:\Program Files\glassfishv3\glassfish\lib"

For now I'll leave this issue as started, rather than fixed, but lower the 
priority.
```

Original comment by `Talash...@gmail.com` on 25 Feb 2010 at 5:29
- Changed state: **Started**
- Added labels: **Priority-Low**
- Removed labels: **Priority-High**

**Comment by GoogleCodeExporter** [comment]
```
This can be considered fixed.  We have extracted the relevant list files from 
the jar
and are using them directly now.
```

Original comment by `Talash...@gmail.com` on 28 Mar 2010 at 5:04
- Changed state: **Fixed**
