### ISSUE TITLE
Backend freezes when testing Delete method in PositionBroker test class

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wiwimi/webagenda#22]
```
What steps will reproduce the problem?
1. Run testPositionBroker
2. Wait for it to hit delete method
3. Watch it hang

What is the expected output? What do you see instead?

The test is partially completed, but it does not finish. The connection
counts down to be removed (which it's not) and it needs to be force-quit'd
to stop.

Console output when it hangs.

DELETE FROM `WebAgenda`.`POSITION` WHERE positionName = 'Admin';
Statement Created
Connection 1: 356 time to remove
Connection 1 is available: false
Connection 1: -4644 time to remove
Connection 1 is available: false

The statement works just fine on its own in the database. I have a hunch
that it's the test itself, something may be stopping it from executing.
HOWEVER
Running the test by itself (just the one method) completes just fine in
that it doesn't hang.

I don't think it's getting caught on any stored procedures.
When I re-ran the test, it started getting hung on the second method call,
the create() test.
```

Original issue reported on code.google.com by `Initial....@gmail.com` on 21 Mar 2010 at 5:34

**Comment by GoogleCodeExporter** [comment]
```
Here's an exception I get after waiting for connection:

exception.DBException: Failed to delete position.
    at persistence.PositionBroker.delete(PositionBroker.java:262)
    at testDB.TestPositionBroker.testDeletePosition(TestPositionBroker.java:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
    at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReferen
ce.java:46)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:467)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.jav
a:197)
Caused by: java.sql.SQLException: Lock wait timeout exceeded; try restarting 
transaction
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1072)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3563)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3495)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2113)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2687)
    at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1647)
    at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1566)
    at persistence.PositionBroker.delete(PositionBroker.java:190)
    ... 25 more


Seems to be locking the table so I can't delete.
```

Original comment by `Initial....@gmail.com` on 21 Mar 2010 at 7:09

**Comment by GoogleCodeExporter** [comment]
```
OK.
I know how this was caused.

For those who get this issue, remember to always call Broker methods using the
getBroker() method! Even if you are in the Broker itself coding, do not use 
class
level calls, use getBroker() then make the method call.
```

Original comment by `Initial....@gmail.com` on 21 Mar 2010 at 7:18

**Comment by GoogleCodeExporter** [comment]
Original comment by `Initial....@gmail.com` on 21 Mar 2010 at 7:19
- Changed state: **Fixed**
